### PR TITLE
Replace conditional assignment to a variable with an if expression

### PR DESCRIPTION
**Pull request by ThibFrgsGmz**
## Change Description

This PR aims to replace several conditional assignments to a variable by if expressions.

## Rationale

The ternary operator is represented by the conditional expression syntax of Python. This is a significant improvement in the case where the conditional expression is :

- short and can be written on a single line

- not difficult (no nested expressions or long boolean strings).

### CODE REVIEW

**Comment by arthaud** [comment]
It's probably bias because I wrote most of this code, but I'm personally not a fan of this.
I feel like in most cases I would rather keep the longer version to make it easier to read.

For instance:
```
return None if self.file_id is None else self.db.files[self.file_id].path
```
This makes it look like this function mostly returns None, but in practice, this is a rare case and the common path is `self.db.files[self.file_id].path`.

Personal biased rant: I actually wished python used the OCaml approach and use `if cond then a else b` which is much more readable because it's left to right. In Python I need to look for the `if` buried in the middle.

**Comment by ThibFrgsGmz** [comment]
I think it's a matter of habit. I wasn't a fan at first, but after using it, I find it much more understandable and elegant with the `return`.

For the example you give, you can simply reverse the `if` condition if you want the `None` to appear last and imply that it almost never happens.

**Comment by ivanperez-keera** [comment]
> ```python
> return None if self.file_id is None else self.db.files[self.file_id].path
> ```
> 
> This makes it look like this function mostly returns None, but in practice, this is a rare case and the common path is `self.db.files[self.file_id].path`.

Can you not just negate the condition? As in:

```python
return self.db.files[self.file_id].path if self.file_id is not None else None
````

I mean, negating conditions is usually not desirable, but if you really want to convey that...

**Comment by ivanperez-keera** [comment]
That being said, I kind of agree that this PR doesn't save us much. We are just factorizing the `return` out. I'd suggest simply not making this change at this point and closing this PR. @arthaud does that seem right to you?

**Comment by arthaud** [comment]
Agreed, thanks for closing.

**Pull request closed without merging**
