### PR TITLE
Fix deprecated getAlignment in function.cpp

### PR DESCRIPTION
**Pull request by serval2412**

### CODE REVIEW

**Comment by ivanperez-keera** [comment]
@serval2412 I've checked that the function disappeared and I have seen other projects make the same change, but I'm struggling to find when or where in LLVM that deprecation was introduced. I can't even find the specific version where that happened.

Can you help me chase that down, just for documentation purposes?

**Comment by serval2412** [comment]
Is there something more I can do here?
Do you think this patch may bring some regression even if it's very straightforward?

**Comment by ivanperez-keera** [comment]
Hi @serval2412 . Nothing in terms of the patch.

If you haven't already, can you please sign one of the two CLAs (whichever applies to your situation): https://github.com/NASA-SW-VnV/ikos/tree/master/doc/contribute and send it to [ikos@lists.nasa.gov](mailto:ikos@lists.nasa.gov), CC-ing [ivan.perezdominguez@nasa.gov](mailto:ivan.perezdominguez@nasa.gov).

**Comment by serval2412** [comment]
Hello,

Sorry, I don't want to sign something like this since I don't measure the impact.
I'm more accustomed to what we can find in Open source. If I take the example of LibreOffice, it would be just a plain email like:
"All of my past & future contributions to Nasa may be licensed under the MPLv2/LGPLv3+ dual license."
Now, the patch is quite straightforward, don't hesitate to use it by changing the author.

**Comment by ivanperez-keera** [comment]
I understand.

**Pull request closed without merging**
