### PR TITLE
Install for centos 8

### PR DESCRIPTION
**Pull request by Rob-McKay**
Added install instructions for installation onto a clean Centos 8 install.

This also includes a small change to get the bootstrap script to work if a new enough version of the Intel TBB library is not present. (The installed version is not new enough by default under Centos 8)

### CODE REVIEW

**Comment by arthaud** [comment]
Hi @Rob-McKay, thanks for the contribution.

Could you please fill the [Contributor License Agreements](https://github.com/NASA-SW-VnV/ikos/tree/master/doc/contribute) and send it to ikos@lists.nasa.gov?

**Comment by Rob-McKay** [comment]
> Hi @Rob-McKay, thanks for the contribution.
> 
> Could you please fill the [Contributor License Agreements](https://github.com/NASA-SW-VnV/ikos/tree/master/doc/contribute) and send it to [ikos@lists.nasa.gov](mailto:ikos@lists.nasa.gov)?

I've emailed the form as requested.

**Comment by ivanperez-keera** [comment]
@Rob-McKay Following up on this. AFAICT, Centos 8 was discontinued. Is that PR something that still makes sense to merge (e.g., if adapted for a successor) or would it be best to close for now?

**Comment by ivanperez-keera** [comment]
Pinging @Rob-McKay . If we get no response, I believe we should close it for the reasons stated [here](https://github.com/NASA-SW-VnV/ikos/pull/164#issuecomment-1647226953).

**Comment by Rob-McKay** [comment]
I would prefer that it was merged to aid others with using other OS's.

**Pull request closed without merging**
